# Generated by Django 4.0.3 on 2022-04-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryexit',
            options={'verbose_name': 'EntryExit', 'verbose_name_plural': 'EntriesExits'},
        ),
        migrations.AlterModelOptions(
            name='hku_member',
            options={'verbose_name': 'HKU Member', 'verbose_name_plural': 'HKU Members'},
        ),
    ]
